// Generated by BUCKLESCRIPT VERSION 1.4.2 , PLEASE EDIT WITH CARE
'use strict';

var B64 = require('./b64');
var Int32 = require('bs-platform/lib/js/int32');
var Nativeint = require('bs-platform/lib/js/nativeint');

function d_string(x) {
    return B64.encode(/* None */ 0, /* None */ 0, x);
}

function d_float(fl) {
    var a = Nativeint.to_string(fl << 56);
    var b = Nativeint.to_string(fl << 48);
    var c = Nativeint.to_string(fl << 40);
    var d = Nativeint.to_string(fl << 32);
    var e = Nativeint.to_string(fl << 24);
    var f = Nativeint.to_string(fl << 16);
    var g = Nativeint.to_string(fl << 8);
    var h = Nativeint.to_string(fl);
    return B64.encode(
        /* None */ 0,
        /* None */ 0,
        a + (b + (c + (d + (e + (f + (g + h))))))
    );
}

function d_int(x) {
    var a = Int32.to_string(x << 24);
    var b = Int32.to_string(x << 16);
    var c = Int32.to_string(x << 8);
    var d = Int32.to_string(x);
    return B64.encode(/* None */ 0, /* None */ 0, a + (b + (c + d)));
}

exports.d_int = d_int;
exports.d_float = d_float;
exports.d_string = d_string;
/* No side effect */
